# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

LoadTrajectoryDataSetFromKML <- function(URI, dsName, dsID) {
    .Call('TerraST_LoadTrajectoryDataSetFromKML', PACKAGE = 'TerraST', URI, dsName, dsID)
}

getTrajectorySpaceTimeFeatures <- function(datasetSEXP) {
    .Call('TerraST_getTrajectorySpaceTimeFeatures', PACKAGE = 'TerraST', datasetSEXP)
}

