# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'  Justa a simple Hello World
oi <- function() {
    invisible(.Call('TerraST_oi', PACKAGE = 'TerraST'))
}

TrajectoryExamples <- function() {
    invisible(.Call('TerraST_TrajectoryExamples', PACKAGE = 'TerraST'))
}

