# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

LoadTrajectoryDataSetFromKML <- function(URI, dsName, dsID) {
    .Call('TerraST_LoadTrajectoryDataSetFromKML', PACKAGE = 'TerraST', URI, dsName, dsID)
}

getTime <- function(datasetSEXP) {
    .Call('TerraST_getTime', PACKAGE = 'TerraST', datasetSEXP)
}

getPoints <- function(datasetSEXP) {
    .Call('TerraST_getPoints', PACKAGE = 'TerraST', datasetSEXP)
}

